name: activito
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  google_sign_in: ^5.1.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.2
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  image_picker: ^0.8.4+2
  firebase_storage: ^10.0.5
  image_cropper: ^1.4.1
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/defaultProfilePic.jpg